server:
  port: 8080

spring:
  application:
    name: blog

  thymeleaf:
    mode: HTML

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123123123

mybatis:
  type-aliases-package: com.weiwu.blog.domain

logging:
  pattern:
    level: info
    com.weiwu.blog.mapper: debug
  file:
    name: log/blog.log

