server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: prod
  application:
    name: blog
  thymeleaf:
    mode: HTML
    cache: false

  # 配置数据源信息
  datasource:  # 数据源类型：HikariCP   # 数据源的相关配置
    driver-class-name: com.mysql.cj.jdbc.Driver         # mysql驱动
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123123123
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 5           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1

## 评论者的默认头像
comments:
  avatar: /images/avatar.jpeg

mybatis:
  type-aliases-package: com.weiwu.blog.domain

logging:
  file:
    name: log/blog.log
  level:
    com.weiwu.blog.mapper: debug

